import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Home(),
        ]),
      ),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 932,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFF6F5F80)),
          child: Stack(
            children: [
              Positioned(
                left: -134.06,
                top: 247,
                child: Transform(
                  transform: Matrix4.identity()
                    ..translate(0.0, 0.0)
                    ..rotateZ(0.62),
                  child: Container(
                    width: 965,
                    height: 554,
                    decoration: BoxDecoration(color: Colors.white),
                  ),
                ),
              ),
              Positioned(
                left: 110.94,
                top: -229,
                child: Transform(
                  transform: Matrix4.identity()
                    ..translate(0.0, 0.0)
                    ..rotateZ(0.62),
                  child: Container(
                    width: 965,
                    height: 554,
                    decoration: BoxDecoration(color: Color(0xFFFF0000)),
                  ),
                ),
              ),
              Positioned(
                left: -139,
                top: 116,
                child: Container(
                  width: 523,
                  height: 523,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 153,
                top: -55,
                child: Container(
                  width: 330,
                  height: 330,
                  decoration: ShapeDecoration(
                    color: Color(0xFFFF8C8C),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 146,
                top: 85,
                child: SizedBox(
                  width: 337,
                  child: Text(
                    'BrandyTrendy',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 32,
                      fontStyle: FontStyle.italic,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w200,
                      height: 0,
                      letterSpacing: -2.24,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 56,
                top: 502,
                child: Container(
                  width: 318,
                  height: 76,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 5,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0xFFFFDC73),
                      ),
                      borderRadius: BorderRadius.circular(19),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 173,
                top: 521,
                child: Text(
                  'Login',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 32,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 56,
                top: 639,
                child: Container(
                  width: 318,
                  height: 76,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 5,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Color(0xFFFFDC73),
                      ),
                      borderRadius: BorderRadius.circular(19),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 152,
                top: 657,
                child: Text(
                  'Register',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 32,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 250,
                top: 750,
                child: SizedBox(
                  width: 180,
                  height: 25,
                  child: Text(
                    '*Use without username',
                    style: TextStyle(
                      color: Color(0xFF8749C7),
                      fontSize: 13,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
